//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CheckPoint05
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrdersRecord
    {
        public int OrderID { get; set; }
        public string CustomerName { get; set; }
        public string ProductName { get; set; }
        public string ManagerName { get; set; }
        public int Amount { get; set; }
        public System.DateTime Date { get; set; }
    }
}
